version: '3.8'
services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: mydb-dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb-dev
    ports:
      - 5434:5432
    restart: always
    networks:
      - lesson
  postgres-test:
    image: postgres:14.4-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: mydb-dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb-dev
    ports:
      - 5433:5432
networks:
  lesson:
